# Generated by Django 3.2.9 on 2021-11-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
