version: '3.8'

services: 
    web: 
        build: .
        command: poetry run python /code/manage.py runserver 0.0.0.0:7000
        volumes:
            - .:/code
        ports: 
            - 7000:7000
        depends_on: 
            - db

    db:
        image: postgres:11
        restart: always
        environment:
            POSTGRES_PASSWORD: admin
        volumes:
            - postgres_data:/var/lib/postgresql/data/

volumes:
    postgres_data:

