# Generated by Django 3.2.9 on 2021-11-11 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20211111_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='can_anonymous_user_access',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='can_family_access',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='can_friend_access',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='can_subcriber_access',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='post', to='post.tag'),
            preserve_default=False,
        ),
    ]
